#' CKAN server URLS and other info
#'
#' @export
#' @examples
#' servers()
#' ckan_info("http://data.gov.au/")
#' ckan_info(servers()[5])
#'
#' # what version is each CKAN server running
#' out <- lapply(servers()[4:6], ckan_info)
#' vapply(out, "[[", "", "ckan_version")
servers <- function() server_urls

server_urls <- c("http://africaopendata.org/",
	"http://www.amsterdamopendata.nl/home",
	"http://daten.berlin.de/",
	"http://opendata.aragon.es/",
	"http://bermuda.io/",
	"https://catalogodatos.gub.uy/",
	"http://data.buenosaires.gob.ar/",
	"http://cities.opendatahub.gr/",
	"http://data.surrey.ca/",
	"http://data.ottawa.ca/",
	"http://www.civicdata.io/",
	"http://datamx.io/",
	"http://opendata.cnmc.es/",
	"http://data.kk.dk/",
	"http://dados.recife.pe.gov.br/",
	"http://dados.gov.br/",
	"http://dados.rs.gov.br/",
	"http://drdsi.jrc.ec.europa.eu/",
	"http://dartportal.leeds.ac.uk/",
	"http://ckan.sabae.jrrk.org/",
	"http://open.canada.ca/en",
	"http://data.bris.ac.uk/data/",
	"http://dataforjapan.org/",
	"http://data.gov.au/",
	"http://www.data.gov/",
	"http://www.data.go.jp/",
	"http://data.gov.ro/",
	"http://data.gov.sk/",
	"http://data.gov.ie/",
	"https://www.data.gv.at/",
	"http://data.norge.no/",
	"http://data.gov.uk/",
	"https://data.overheid.nl/",
	"http://data.rio.rj.gov.br/",
	"http://data.nsw.gov.au/",
	"http://datagm.org.uk/",
	"http://dataportals.org/",
	"http://data.salzburgerland.com/",
	"http://www.dati.gov.it/",
	"http://datapoa.com.br/",
	"http://datamx.io/",
	"http://datosabiertos.ec/",
	"http://datos.gob.mx/",
	"http://datosabiertos.malaga.eu/",
	"https://edx.netl.doe.gov/",
	"http://data.edostate.gov.ng/",
	"http://data.denvergov.org/",
	"http://open-data.europa.eu/en/data/",
	"http://ckan.gsi.go.jp/",
	"https://data.glasgow.gov.uk/",
	"http://gong.io/",
	"https://www.govdata.de/",
	"http://data.grcity.us/",
	"http://data.graz.gv.at/",
	"http://open-data.okfn.gr/",
	"http://opendatahub.gr/",
	"http://www.healthdata.gov/",
	"http://www.hri.fi/fi/",
	"http://data.codeforhouston.com/",
	"https://data.hdx.rwlabs.org/",
	"http://data.lexingtonky.gov/",
	"http://www.opendata.provincia.roma.it/",
	"http://datameti.go.jp/data/",
	"https://gisdata.mn.gov/",
	"http://data.linz.gv.at/",
	"http://donnees.ville.montreal.qc.ca/",
	"http://geothermaldata.org/",
	"https://data.noaa.gov/dataset",
	"http://www.nosdonnees.fr/",
	"https://offenedaten.de/",
	"http://www.odaa.dk/",
	"http://www.offene-daten.me/",
	"http://opendatacanarias.es/",
	"http://www.odaa.dk/",
	"http://dati.toscana.it/",
	"http://opendatagortynia.gr/",
	"http://www.opendatahub.it/",
	"http://data.ug/",
	"http://datameti.go.jp/",
	"http://data.kk.dk/",
	"http://transparenz.hamburg.de/open-data/",
	"http://data.openva.com/",
	"http://dati.trentino.it/",
	"http://portal.openbelgium.be/",
	"http://opencolorado.org/",
	"http://opendata.caceres.es/",
	"http://opendata.lisra.jp/",
	"http://opendata.caceres.es/",
	"http://www.opendata-hro.de/",
	"http://opendata.hu/",
	"http://opendata.awt.be/",
	"http://opendatareno.org/",
	"http://hubofdata.ru/",
	"http://opendatadc.org/",
	"http://www.datos.misiones.gov.ar/",
	"http://www.openumea.se/",
	"http://opingogn.is/",
	"http://datospublicos.gob.ar/",
	"http://publicdata.eu/",
	"http://opendata.comune.bari.it/",
	"http://www.daten.rlp.de/",
	"https://data.qld.gov.au/",
	"http://catalogue.datalocale.fr/",
	"http://donnees.ville.sherbrooke.qc.ca/",
	"http://rotterdamopendata.nl/dataset",
	"http://data.cityofsantacruz.com/",
	"https://data.sa.gov.au/",
	"http://opendata.admin.ch/",
	"http://data.tainan.gov.tw/",
	"http://datahub.io/",
	"http://iatiregistry.org/",
	"http://dadosabertos.senado.gov.br/",
	"http://oppnadata.se/",
	"http://data.yokohamaopendata.jp/",
	"http://udct-data.aigid.jp/")
